version: '3'
networks:
  distributed:
    driver: bridge
services:
  retro-games-api-1: # FastAPI application
    container_name: retro-games-api-1
    build: ./api
    # deploy:
    #   replicas: 3
    ports:
      - "801:8000"
    environment:
      - MONGO_URI=mongodb://mongodb:27017
      - SECRET_KEY=7a659b3e5f6f62768342612137313c6ced900d56b49acccf11c86185e4af91ec
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=525600
    volumes:
      - ./api:/app
    networks:
      - distributed
    depends_on:
      - mongodb
  retro-games-api-2: # FastAPI application
    container_name: retro-games-api-2
    build: ./api
    # deploy:
    #   replicas: 3
    ports:
      - "802:8000"
    environment:
      - MONGO_URI=mongodb://mongodb:27017
      - SECRET_KEY=7a659b3e5f6f62768342612137313c6ced900d56b49acccf11c86185e4af91ec
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=525600
    volumes:
      - ./api:/app
    networks:
      - distributed
    depends_on:
      - mongodb
  mongodb: # MongoDB database
    container_name: mongodb
    image: mongo
    ports:
      - "2718:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - distributed
  nginx: # NGINX load balancer
    container_name: mynginx
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - distributed
    depends_on:
      - retro-games-api-1
      - retro-games-api-2
  retro-games-kafka-zookeeper:
    container_name: retro-games-kafka-zookeeper
    image: confluentinc/cp-zookeeper:latest
    # ports:
      # - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - distributed
  retro-games-kafka-broker:
    container_name: retro-games-kafka-broker
    image: confluentinc/cp-kafka:latest
    depends_on:
      - retro-games-kafka-zookeeper
    ports:
      - "29092:29092" # Main port for Kafka # Might not be
      # - "9092:9092"
      # - "9101:9101"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: retro-games-kafka-zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092, PLAINTEXT_INTERNAL://retro-games-kafka-broker:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      # KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      # KAFKA_JMX_PORT: 9101
      # KAFKA_JMX_HOSTNAME: localhost
    networks:
      - distributed
volumes:
  mongodb_data: